// Generated by gencpp from file robot_audio/AwakeResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_AWAKERESPONSE_H
#define ROBOT_AUDIO_MESSAGE_AWAKERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_audio
{
template <class ContainerAllocator>
struct AwakeResponse_
{
  typedef AwakeResponse_<ContainerAllocator> Type;

  AwakeResponse_()
    : awake_flag(false)  {
    }
  AwakeResponse_(const ContainerAllocator& _alloc)
    : awake_flag(false)  {
  (void)_alloc;
    }



   typedef uint8_t _awake_flag_type;
  _awake_flag_type awake_flag;





  typedef boost::shared_ptr< ::robot_audio::AwakeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_audio::AwakeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AwakeResponse_

typedef ::robot_audio::AwakeResponse_<std::allocator<void> > AwakeResponse;

typedef boost::shared_ptr< ::robot_audio::AwakeResponse > AwakeResponsePtr;
typedef boost::shared_ptr< ::robot_audio::AwakeResponse const> AwakeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_audio::AwakeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_audio::AwakeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_audio::AwakeResponse_<ContainerAllocator1> & lhs, const ::robot_audio::AwakeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.awake_flag == rhs.awake_flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_audio::AwakeResponse_<ContainerAllocator1> & lhs, const ::robot_audio::AwakeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_audio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_audio::AwakeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_audio::AwakeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::AwakeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::AwakeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::AwakeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::AwakeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_audio::AwakeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba26fa73d43b7a318fdd106444479e6e";
  }

  static const char* value(const ::robot_audio::AwakeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba26fa73d43b7a31ULL;
  static const uint64_t static_value2 = 0x8fdd106444479e6eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_audio::AwakeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_audio/AwakeResponse";
  }

  static const char* value(const ::robot_audio::AwakeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_audio::AwakeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool awake_flag\n"
"\n"
;
  }

  static const char* value(const ::robot_audio::AwakeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_audio::AwakeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.awake_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AwakeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_audio::AwakeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_audio::AwakeResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "awake_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.awake_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_AWAKERESPONSE_H
