// Generated by gencpp from file robot_audio/Awake.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_AWAKE_H
#define ROBOT_AUDIO_MESSAGE_AWAKE_H

#include <ros/service_traits.h>


#include <robot_audio/AwakeRequest.h>
#include <robot_audio/AwakeResponse.h>


namespace robot_audio
{

struct Awake
{

typedef AwakeRequest Request;
typedef AwakeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Awake
} // namespace robot_audio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_audio::Awake > {
  static const char* value()
  {
    return "346f56948fa329d395224adefd3ff2c1";
  }

  static const char* value(const ::robot_audio::Awake&) { return value(); }
};

template<>
struct DataType< ::robot_audio::Awake > {
  static const char* value()
  {
    return "robot_audio/Awake";
  }

  static const char* value(const ::robot_audio::Awake&) { return value(); }
};


// service_traits::MD5Sum< ::robot_audio::AwakeRequest> should match
// service_traits::MD5Sum< ::robot_audio::Awake >
template<>
struct MD5Sum< ::robot_audio::AwakeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_audio::Awake >::value();
  }
  static const char* value(const ::robot_audio::AwakeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_audio::AwakeRequest> should match
// service_traits::DataType< ::robot_audio::Awake >
template<>
struct DataType< ::robot_audio::AwakeRequest>
{
  static const char* value()
  {
    return DataType< ::robot_audio::Awake >::value();
  }
  static const char* value(const ::robot_audio::AwakeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_audio::AwakeResponse> should match
// service_traits::MD5Sum< ::robot_audio::Awake >
template<>
struct MD5Sum< ::robot_audio::AwakeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_audio::Awake >::value();
  }
  static const char* value(const ::robot_audio::AwakeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_audio::AwakeResponse> should match
// service_traits::DataType< ::robot_audio::Awake >
template<>
struct DataType< ::robot_audio::AwakeResponse>
{
  static const char* value()
  {
    return DataType< ::robot_audio::Awake >::value();
  }
  static const char* value(const ::robot_audio::AwakeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_AWAKE_H
