// Generated by gencpp from file robot_audio/CollectRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_COLLECTREQUEST_H
#define ROBOT_AUDIO_MESSAGE_COLLECTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_audio
{
template <class ContainerAllocator>
struct CollectRequest_
{
  typedef CollectRequest_<ContainerAllocator> Type;

  CollectRequest_()
    : collect_flag(false)  {
    }
  CollectRequest_(const ContainerAllocator& _alloc)
    : collect_flag(false)  {
  (void)_alloc;
    }



   typedef uint8_t _collect_flag_type;
  _collect_flag_type collect_flag;





  typedef boost::shared_ptr< ::robot_audio::CollectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_audio::CollectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CollectRequest_

typedef ::robot_audio::CollectRequest_<std::allocator<void> > CollectRequest;

typedef boost::shared_ptr< ::robot_audio::CollectRequest > CollectRequestPtr;
typedef boost::shared_ptr< ::robot_audio::CollectRequest const> CollectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_audio::CollectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_audio::CollectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_audio::CollectRequest_<ContainerAllocator1> & lhs, const ::robot_audio::CollectRequest_<ContainerAllocator2> & rhs)
{
  return lhs.collect_flag == rhs.collect_flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_audio::CollectRequest_<ContainerAllocator1> & lhs, const ::robot_audio::CollectRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_audio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_audio::CollectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_audio::CollectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::CollectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::CollectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::CollectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::CollectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_audio::CollectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e5a4c2fde512defbeb6f36ecc721e7f";
  }

  static const char* value(const ::robot_audio::CollectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e5a4c2fde512defULL;
  static const uint64_t static_value2 = 0xbeb6f36ecc721e7fULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_audio::CollectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_audio/CollectRequest";
  }

  static const char* value(const ::robot_audio::CollectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_audio::CollectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool collect_flag\n"
;
  }

  static const char* value(const ::robot_audio::CollectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_audio::CollectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.collect_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CollectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_audio::CollectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_audio::CollectRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "collect_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.collect_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_COLLECTREQUEST_H
