// Generated by gencpp from file robot_audio/Collect.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_COLLECT_H
#define ROBOT_AUDIO_MESSAGE_COLLECT_H

#include <ros/service_traits.h>


#include <robot_audio/CollectRequest.h>
#include <robot_audio/CollectResponse.h>


namespace robot_audio
{

struct Collect
{

typedef CollectRequest Request;
typedef CollectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Collect
} // namespace robot_audio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_audio::Collect > {
  static const char* value()
  {
    return "10ccb23b7c8752a359f2fdb188e7b775";
  }

  static const char* value(const ::robot_audio::Collect&) { return value(); }
};

template<>
struct DataType< ::robot_audio::Collect > {
  static const char* value()
  {
    return "robot_audio/Collect";
  }

  static const char* value(const ::robot_audio::Collect&) { return value(); }
};


// service_traits::MD5Sum< ::robot_audio::CollectRequest> should match
// service_traits::MD5Sum< ::robot_audio::Collect >
template<>
struct MD5Sum< ::robot_audio::CollectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_audio::Collect >::value();
  }
  static const char* value(const ::robot_audio::CollectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_audio::CollectRequest> should match
// service_traits::DataType< ::robot_audio::Collect >
template<>
struct DataType< ::robot_audio::CollectRequest>
{
  static const char* value()
  {
    return DataType< ::robot_audio::Collect >::value();
  }
  static const char* value(const ::robot_audio::CollectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_audio::CollectResponse> should match
// service_traits::MD5Sum< ::robot_audio::Collect >
template<>
struct MD5Sum< ::robot_audio::CollectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_audio::Collect >::value();
  }
  static const char* value(const ::robot_audio::CollectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_audio::CollectResponse> should match
// service_traits::DataType< ::robot_audio::Collect >
template<>
struct DataType< ::robot_audio::CollectResponse>
{
  static const char* value()
  {
    return DataType< ::robot_audio::Collect >::value();
  }
  static const char* value(const ::robot_audio::CollectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_COLLECT_H
