// Generated by gencpp from file robot_audio/CollectResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_COLLECTRESPONSE_H
#define ROBOT_AUDIO_MESSAGE_COLLECTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_audio
{
template <class ContainerAllocator>
struct CollectResponse_
{
  typedef CollectResponse_<ContainerAllocator> Type;

  CollectResponse_()
    : voice_filename()  {
    }
  CollectResponse_(const ContainerAllocator& _alloc)
    : voice_filename(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _voice_filename_type;
  _voice_filename_type voice_filename;





  typedef boost::shared_ptr< ::robot_audio::CollectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_audio::CollectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CollectResponse_

typedef ::robot_audio::CollectResponse_<std::allocator<void> > CollectResponse;

typedef boost::shared_ptr< ::robot_audio::CollectResponse > CollectResponsePtr;
typedef boost::shared_ptr< ::robot_audio::CollectResponse const> CollectResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_audio::CollectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_audio::CollectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_audio::CollectResponse_<ContainerAllocator1> & lhs, const ::robot_audio::CollectResponse_<ContainerAllocator2> & rhs)
{
  return lhs.voice_filename == rhs.voice_filename;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_audio::CollectResponse_<ContainerAllocator1> & lhs, const ::robot_audio::CollectResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_audio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_audio::CollectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_audio::CollectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::CollectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::CollectResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::CollectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::CollectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_audio::CollectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54891ae46df7ead06046f88b1fa92aa3";
  }

  static const char* value(const ::robot_audio::CollectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54891ae46df7ead0ULL;
  static const uint64_t static_value2 = 0x6046f88b1fa92aa3ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_audio::CollectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_audio/CollectResponse";
  }

  static const char* value(const ::robot_audio::CollectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_audio::CollectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string voice_filename\n"
"\n"
;
  }

  static const char* value(const ::robot_audio::CollectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_audio::CollectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.voice_filename);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CollectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_audio::CollectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_audio::CollectResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "voice_filename: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.voice_filename);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_COLLECTRESPONSE_H
