// Generated by gencpp from file robot_audio/ControlRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_CONTROLREQUEST_H
#define ROBOT_AUDIO_MESSAGE_CONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_audio
{
template <class ContainerAllocator>
struct ControlRequest_
{
  typedef ControlRequest_<ContainerAllocator> Type;

  ControlRequest_()
    : controlInfo()
    , value(0.0)  {
    }
  ControlRequest_(const ContainerAllocator& _alloc)
    : controlInfo(_alloc)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _controlInfo_type;
  _controlInfo_type controlInfo;

   typedef float _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::robot_audio::ControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_audio::ControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ControlRequest_

typedef ::robot_audio::ControlRequest_<std::allocator<void> > ControlRequest;

typedef boost::shared_ptr< ::robot_audio::ControlRequest > ControlRequestPtr;
typedef boost::shared_ptr< ::robot_audio::ControlRequest const> ControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_audio::ControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_audio::ControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_audio::ControlRequest_<ContainerAllocator1> & lhs, const ::robot_audio::ControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.controlInfo == rhs.controlInfo &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_audio::ControlRequest_<ContainerAllocator1> & lhs, const ::robot_audio::ControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_audio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_audio::ControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_audio::ControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::ControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::ControlRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::ControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::ControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_audio::ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "502b98fa0e36150f0dd5676f0ecc7150";
  }

  static const char* value(const ::robot_audio::ControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x502b98fa0e36150fULL;
  static const uint64_t static_value2 = 0x0dd5676f0ecc7150ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_audio::ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_audio/ControlRequest";
  }

  static const char* value(const ::robot_audio::ControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_audio::ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] controlInfo\n"
"float32 value\n"
;
  }

  static const char* value(const ::robot_audio::ControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_audio::ControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controlInfo);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_audio::ControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_audio::ControlRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "controlInfo: ";
    if (v.controlInfo.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.controlInfo.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.controlInfo[i]);
    }
    if (v.controlInfo.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_CONTROLREQUEST_H
