// Generated by gencpp from file robot_audio/Control.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_CONTROL_H
#define ROBOT_AUDIO_MESSAGE_CONTROL_H

#include <ros/service_traits.h>


#include <robot_audio/ControlRequest.h>
#include <robot_audio/ControlResponse.h>


namespace robot_audio
{

struct Control
{

typedef ControlRequest Request;
typedef ControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Control
} // namespace robot_audio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_audio::Control > {
  static const char* value()
  {
    return "d9d592028a39d44769bfd310193595a8";
  }

  static const char* value(const ::robot_audio::Control&) { return value(); }
};

template<>
struct DataType< ::robot_audio::Control > {
  static const char* value()
  {
    return "robot_audio/Control";
  }

  static const char* value(const ::robot_audio::Control&) { return value(); }
};


// service_traits::MD5Sum< ::robot_audio::ControlRequest> should match
// service_traits::MD5Sum< ::robot_audio::Control >
template<>
struct MD5Sum< ::robot_audio::ControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_audio::Control >::value();
  }
  static const char* value(const ::robot_audio::ControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_audio::ControlRequest> should match
// service_traits::DataType< ::robot_audio::Control >
template<>
struct DataType< ::robot_audio::ControlRequest>
{
  static const char* value()
  {
    return DataType< ::robot_audio::Control >::value();
  }
  static const char* value(const ::robot_audio::ControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_audio::ControlResponse> should match
// service_traits::MD5Sum< ::robot_audio::Control >
template<>
struct MD5Sum< ::robot_audio::ControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_audio::Control >::value();
  }
  static const char* value(const ::robot_audio::ControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_audio::ControlResponse> should match
// service_traits::DataType< ::robot_audio::Control >
template<>
struct DataType< ::robot_audio::ControlResponse>
{
  static const char* value()
  {
    return DataType< ::robot_audio::Control >::value();
  }
  static const char* value(const ::robot_audio::ControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_CONTROL_H
