// Generated by gencpp from file robot_audio/Nav.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_NAV_H
#define ROBOT_AUDIO_MESSAGE_NAV_H

#include <ros/service_traits.h>


#include <robot_audio/NavRequest.h>
#include <robot_audio/NavResponse.h>


namespace robot_audio
{

struct Nav
{

typedef NavRequest Request;
typedef NavResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Nav
} // namespace robot_audio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_audio::Nav > {
  static const char* value()
  {
    return "a5777d99dbd597cc68511d66738b3956";
  }

  static const char* value(const ::robot_audio::Nav&) { return value(); }
};

template<>
struct DataType< ::robot_audio::Nav > {
  static const char* value()
  {
    return "robot_audio/Nav";
  }

  static const char* value(const ::robot_audio::Nav&) { return value(); }
};


// service_traits::MD5Sum< ::robot_audio::NavRequest> should match
// service_traits::MD5Sum< ::robot_audio::Nav >
template<>
struct MD5Sum< ::robot_audio::NavRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_audio::Nav >::value();
  }
  static const char* value(const ::robot_audio::NavRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_audio::NavRequest> should match
// service_traits::DataType< ::robot_audio::Nav >
template<>
struct DataType< ::robot_audio::NavRequest>
{
  static const char* value()
  {
    return DataType< ::robot_audio::Nav >::value();
  }
  static const char* value(const ::robot_audio::NavRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_audio::NavResponse> should match
// service_traits::MD5Sum< ::robot_audio::Nav >
template<>
struct MD5Sum< ::robot_audio::NavResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_audio::Nav >::value();
  }
  static const char* value(const ::robot_audio::NavResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_audio::NavResponse> should match
// service_traits::DataType< ::robot_audio::Nav >
template<>
struct DataType< ::robot_audio::NavResponse>
{
  static const char* value()
  {
    return DataType< ::robot_audio::Nav >::value();
  }
  static const char* value(const ::robot_audio::NavResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_NAV_H
