// Generated by gencpp from file robot_audio/NavResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_NAVRESPONSE_H
#define ROBOT_AUDIO_MESSAGE_NAVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_audio
{
template <class ContainerAllocator>
struct NavResponse_
{
  typedef NavResponse_<ContainerAllocator> Type;

  NavResponse_()
    : position()  {
    }
  NavResponse_(const ContainerAllocator& _alloc)
    : position(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::robot_audio::NavResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_audio::NavResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NavResponse_

typedef ::robot_audio::NavResponse_<std::allocator<void> > NavResponse;

typedef boost::shared_ptr< ::robot_audio::NavResponse > NavResponsePtr;
typedef boost::shared_ptr< ::robot_audio::NavResponse const> NavResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_audio::NavResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_audio::NavResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_audio::NavResponse_<ContainerAllocator1> & lhs, const ::robot_audio::NavResponse_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_audio::NavResponse_<ContainerAllocator1> & lhs, const ::robot_audio::NavResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_audio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_audio::NavResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_audio::NavResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::NavResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::NavResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::NavResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::NavResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_audio::NavResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6afdd327a64a50f94a7d3a2de5435e3";
  }

  static const char* value(const ::robot_audio::NavResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6afdd327a64a50fULL;
  static const uint64_t static_value2 = 0x94a7d3a2de5435e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_audio::NavResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_audio/NavResponse";
  }

  static const char* value(const ::robot_audio::NavResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_audio::NavResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string position\n"
"\n"
;
  }

  static const char* value(const ::robot_audio::NavResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_audio::NavResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_audio::NavResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_audio::NavResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_NAVRESPONSE_H
