// Generated by gencpp from file robot_audio/NavRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_NAVREQUEST_H
#define ROBOT_AUDIO_MESSAGE_NAVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_audio
{
template <class ContainerAllocator>
struct NavRequest_
{
  typedef NavRequest_<ContainerAllocator> Type;

  NavRequest_()
    : nav_order()  {
    }
  NavRequest_(const ContainerAllocator& _alloc)
    : nav_order(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _nav_order_type;
  _nav_order_type nav_order;





  typedef boost::shared_ptr< ::robot_audio::NavRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_audio::NavRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NavRequest_

typedef ::robot_audio::NavRequest_<std::allocator<void> > NavRequest;

typedef boost::shared_ptr< ::robot_audio::NavRequest > NavRequestPtr;
typedef boost::shared_ptr< ::robot_audio::NavRequest const> NavRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_audio::NavRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_audio::NavRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_audio::NavRequest_<ContainerAllocator1> & lhs, const ::robot_audio::NavRequest_<ContainerAllocator2> & rhs)
{
  return lhs.nav_order == rhs.nav_order;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_audio::NavRequest_<ContainerAllocator1> & lhs, const ::robot_audio::NavRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_audio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_audio::NavRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_audio::NavRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::NavRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::NavRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::NavRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::NavRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_audio::NavRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "038c2ccb2af0905079318ffc740cb9a6";
  }

  static const char* value(const ::robot_audio::NavRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x038c2ccb2af09050ULL;
  static const uint64_t static_value2 = 0x79318ffc740cb9a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_audio::NavRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_audio/NavRequest";
  }

  static const char* value(const ::robot_audio::NavRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_audio::NavRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string nav_order\n"
;
  }

  static const char* value(const ::robot_audio::NavRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_audio::NavRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nav_order);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_audio::NavRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_audio::NavRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "nav_order: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.nav_order);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_NAVREQUEST_H
