// Generated by gencpp from file robot_audio/robot_tts.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_ROBOT_TTS_H
#define ROBOT_AUDIO_MESSAGE_ROBOT_TTS_H

#include <ros/service_traits.h>


#include <robot_audio/robot_ttsRequest.h>
#include <robot_audio/robot_ttsResponse.h>


namespace robot_audio
{

struct robot_tts
{

typedef robot_ttsRequest Request;
typedef robot_ttsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_tts
} // namespace robot_audio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_audio::robot_tts > {
  static const char* value()
  {
    return "2ad2a7e28f20ec853b183153ee6b6d2d";
  }

  static const char* value(const ::robot_audio::robot_tts&) { return value(); }
};

template<>
struct DataType< ::robot_audio::robot_tts > {
  static const char* value()
  {
    return "robot_audio/robot_tts";
  }

  static const char* value(const ::robot_audio::robot_tts&) { return value(); }
};


// service_traits::MD5Sum< ::robot_audio::robot_ttsRequest> should match
// service_traits::MD5Sum< ::robot_audio::robot_tts >
template<>
struct MD5Sum< ::robot_audio::robot_ttsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_audio::robot_tts >::value();
  }
  static const char* value(const ::robot_audio::robot_ttsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_audio::robot_ttsRequest> should match
// service_traits::DataType< ::robot_audio::robot_tts >
template<>
struct DataType< ::robot_audio::robot_ttsRequest>
{
  static const char* value()
  {
    return DataType< ::robot_audio::robot_tts >::value();
  }
  static const char* value(const ::robot_audio::robot_ttsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_audio::robot_ttsResponse> should match
// service_traits::MD5Sum< ::robot_audio::robot_tts >
template<>
struct MD5Sum< ::robot_audio::robot_ttsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_audio::robot_tts >::value();
  }
  static const char* value(const ::robot_audio::robot_ttsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_audio::robot_ttsResponse> should match
// service_traits::DataType< ::robot_audio::robot_tts >
template<>
struct DataType< ::robot_audio::robot_ttsResponse>
{
  static const char* value()
  {
    return DataType< ::robot_audio::robot_tts >::value();
  }
  static const char* value(const ::robot_audio::robot_ttsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_ROBOT_TTS_H
