// Generated by gencpp from file robot_audio/robot_iatRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_ROBOT_IATREQUEST_H
#define ROBOT_AUDIO_MESSAGE_ROBOT_IATREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_audio
{
template <class ContainerAllocator>
struct robot_iatRequest_
{
  typedef robot_iatRequest_<ContainerAllocator> Type;

  robot_iatRequest_()
    : audiopath()  {
    }
  robot_iatRequest_(const ContainerAllocator& _alloc)
    : audiopath(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _audiopath_type;
  _audiopath_type audiopath;





  typedef boost::shared_ptr< ::robot_audio::robot_iatRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_audio::robot_iatRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robot_iatRequest_

typedef ::robot_audio::robot_iatRequest_<std::allocator<void> > robot_iatRequest;

typedef boost::shared_ptr< ::robot_audio::robot_iatRequest > robot_iatRequestPtr;
typedef boost::shared_ptr< ::robot_audio::robot_iatRequest const> robot_iatRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_audio::robot_iatRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_audio::robot_iatRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_audio::robot_iatRequest_<ContainerAllocator1> & lhs, const ::robot_audio::robot_iatRequest_<ContainerAllocator2> & rhs)
{
  return lhs.audiopath == rhs.audiopath;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_audio::robot_iatRequest_<ContainerAllocator1> & lhs, const ::robot_audio::robot_iatRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_audio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_audio::robot_iatRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_audio::robot_iatRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::robot_iatRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::robot_iatRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::robot_iatRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::robot_iatRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_audio::robot_iatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e404094a9595b4fe3761b0ec9dfd6df";
  }

  static const char* value(const ::robot_audio::robot_iatRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e404094a9595b4fULL;
  static const uint64_t static_value2 = 0xe3761b0ec9dfd6dfULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_audio::robot_iatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_audio/robot_iatRequest";
  }

  static const char* value(const ::robot_audio::robot_iatRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_audio::robot_iatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string audiopath\n"
;
  }

  static const char* value(const ::robot_audio::robot_iatRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_audio::robot_iatRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.audiopath);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_iatRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_audio::robot_iatRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_audio::robot_iatRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "audiopath: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.audiopath);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_ROBOT_IATREQUEST_H
