// Generated by gencpp from file robot_audio/robot_semantemeRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_ROBOT_SEMANTEMEREQUEST_H
#define ROBOT_AUDIO_MESSAGE_ROBOT_SEMANTEMEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_audio
{
template <class ContainerAllocator>
struct robot_semantemeRequest_
{
  typedef robot_semantemeRequest_<ContainerAllocator> Type;

  robot_semantemeRequest_()
    : mode(0)
    , textorpath()  {
    }
  robot_semantemeRequest_(const ContainerAllocator& _alloc)
    : mode(0)
    , textorpath(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _mode_type;
  _mode_type mode;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _textorpath_type;
  _textorpath_type textorpath;





  typedef boost::shared_ptr< ::robot_audio::robot_semantemeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_audio::robot_semantemeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robot_semantemeRequest_

typedef ::robot_audio::robot_semantemeRequest_<std::allocator<void> > robot_semantemeRequest;

typedef boost::shared_ptr< ::robot_audio::robot_semantemeRequest > robot_semantemeRequestPtr;
typedef boost::shared_ptr< ::robot_audio::robot_semantemeRequest const> robot_semantemeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_audio::robot_semantemeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_audio::robot_semantemeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_audio::robot_semantemeRequest_<ContainerAllocator1> & lhs, const ::robot_audio::robot_semantemeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.textorpath == rhs.textorpath;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_audio::robot_semantemeRequest_<ContainerAllocator1> & lhs, const ::robot_audio::robot_semantemeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_audio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_audio::robot_semantemeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_audio::robot_semantemeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::robot_semantemeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::robot_semantemeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::robot_semantemeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::robot_semantemeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_audio::robot_semantemeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d317f79ad89a19b72d1e4794651dfbde";
  }

  static const char* value(const ::robot_audio::robot_semantemeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd317f79ad89a19b7ULL;
  static const uint64_t static_value2 = 0x2d1e4794651dfbdeULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_audio::robot_semantemeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_audio/robot_semantemeRequest";
  }

  static const char* value(const ::robot_audio::robot_semantemeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_audio::robot_semantemeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 mode\n"
"string textorpath\n"
;
  }

  static const char* value(const ::robot_audio::robot_semantemeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_audio::robot_semantemeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.textorpath);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_semantemeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_audio::robot_semantemeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_audio::robot_semantemeRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "textorpath: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.textorpath);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_ROBOT_SEMANTEMEREQUEST_H
