// Generated by gencpp from file robot_audio/robot_semanteme.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_ROBOT_SEMANTEME_H
#define ROBOT_AUDIO_MESSAGE_ROBOT_SEMANTEME_H

#include <ros/service_traits.h>


#include <robot_audio/robot_semantemeRequest.h>
#include <robot_audio/robot_semantemeResponse.h>


namespace robot_audio
{

struct robot_semanteme
{

typedef robot_semantemeRequest Request;
typedef robot_semantemeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_semanteme
} // namespace robot_audio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_audio::robot_semanteme > {
  static const char* value()
  {
    return "137f770ca875cecbf1fccdae0ac71f77";
  }

  static const char* value(const ::robot_audio::robot_semanteme&) { return value(); }
};

template<>
struct DataType< ::robot_audio::robot_semanteme > {
  static const char* value()
  {
    return "robot_audio/robot_semanteme";
  }

  static const char* value(const ::robot_audio::robot_semanteme&) { return value(); }
};


// service_traits::MD5Sum< ::robot_audio::robot_semantemeRequest> should match
// service_traits::MD5Sum< ::robot_audio::robot_semanteme >
template<>
struct MD5Sum< ::robot_audio::robot_semantemeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_audio::robot_semanteme >::value();
  }
  static const char* value(const ::robot_audio::robot_semantemeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_audio::robot_semantemeRequest> should match
// service_traits::DataType< ::robot_audio::robot_semanteme >
template<>
struct DataType< ::robot_audio::robot_semantemeRequest>
{
  static const char* value()
  {
    return DataType< ::robot_audio::robot_semanteme >::value();
  }
  static const char* value(const ::robot_audio::robot_semantemeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_audio::robot_semantemeResponse> should match
// service_traits::MD5Sum< ::robot_audio::robot_semanteme >
template<>
struct MD5Sum< ::robot_audio::robot_semantemeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_audio::robot_semanteme >::value();
  }
  static const char* value(const ::robot_audio::robot_semantemeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_audio::robot_semantemeResponse> should match
// service_traits::DataType< ::robot_audio::robot_semanteme >
template<>
struct DataType< ::robot_audio::robot_semantemeResponse>
{
  static const char* value()
  {
    return DataType< ::robot_audio::robot_semanteme >::value();
  }
  static const char* value(const ::robot_audio::robot_semantemeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_ROBOT_SEMANTEME_H
