// Generated by gencpp from file robot_audio/robot_ttsRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_ROBOT_TTSREQUEST_H
#define ROBOT_AUDIO_MESSAGE_ROBOT_TTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_audio
{
template <class ContainerAllocator>
struct robot_ttsRequest_
{
  typedef robot_ttsRequest_<ContainerAllocator> Type;

  robot_ttsRequest_()
    : text()
    , play(false)  {
    }
  robot_ttsRequest_(const ContainerAllocator& _alloc)
    : text(_alloc)
    , play(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _text_type;
  _text_type text;

   typedef uint8_t _play_type;
  _play_type play;





  typedef boost::shared_ptr< ::robot_audio::robot_ttsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_audio::robot_ttsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robot_ttsRequest_

typedef ::robot_audio::robot_ttsRequest_<std::allocator<void> > robot_ttsRequest;

typedef boost::shared_ptr< ::robot_audio::robot_ttsRequest > robot_ttsRequestPtr;
typedef boost::shared_ptr< ::robot_audio::robot_ttsRequest const> robot_ttsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_audio::robot_ttsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_audio::robot_ttsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_audio::robot_ttsRequest_<ContainerAllocator1> & lhs, const ::robot_audio::robot_ttsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.text == rhs.text &&
    lhs.play == rhs.play;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_audio::robot_ttsRequest_<ContainerAllocator1> & lhs, const ::robot_audio::robot_ttsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_audio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_audio::robot_ttsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_audio::robot_ttsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::robot_ttsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::robot_ttsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::robot_ttsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::robot_ttsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_audio::robot_ttsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "121e542c3e7ca17ad7d209752fdda273";
  }

  static const char* value(const ::robot_audio::robot_ttsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x121e542c3e7ca17aULL;
  static const uint64_t static_value2 = 0xd7d209752fdda273ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_audio::robot_ttsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_audio/robot_ttsRequest";
  }

  static const char* value(const ::robot_audio::robot_ttsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_audio::robot_ttsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text\n"
"bool play\n"
;
  }

  static const char* value(const ::robot_audio::robot_ttsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_audio::robot_ttsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
      stream.next(m.play);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_ttsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_audio::robot_ttsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_audio::robot_ttsRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.text);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "play: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.play);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_ROBOT_TTSREQUEST_H
