// Generated by gencpp from file robot_audio/robot_iat.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_ROBOT_IAT_H
#define ROBOT_AUDIO_MESSAGE_ROBOT_IAT_H

#include <ros/service_traits.h>


#include <robot_audio/robot_iatRequest.h>
#include <robot_audio/robot_iatResponse.h>


namespace robot_audio
{

struct robot_iat
{

typedef robot_iatRequest Request;
typedef robot_iatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_iat
} // namespace robot_audio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_audio::robot_iat > {
  static const char* value()
  {
    return "318b42904b3fd33a38a273170db5f135";
  }

  static const char* value(const ::robot_audio::robot_iat&) { return value(); }
};

template<>
struct DataType< ::robot_audio::robot_iat > {
  static const char* value()
  {
    return "robot_audio/robot_iat";
  }

  static const char* value(const ::robot_audio::robot_iat&) { return value(); }
};


// service_traits::MD5Sum< ::robot_audio::robot_iatRequest> should match
// service_traits::MD5Sum< ::robot_audio::robot_iat >
template<>
struct MD5Sum< ::robot_audio::robot_iatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_audio::robot_iat >::value();
  }
  static const char* value(const ::robot_audio::robot_iatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_audio::robot_iatRequest> should match
// service_traits::DataType< ::robot_audio::robot_iat >
template<>
struct DataType< ::robot_audio::robot_iatRequest>
{
  static const char* value()
  {
    return DataType< ::robot_audio::robot_iat >::value();
  }
  static const char* value(const ::robot_audio::robot_iatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_audio::robot_iatResponse> should match
// service_traits::MD5Sum< ::robot_audio::robot_iat >
template<>
struct MD5Sum< ::robot_audio::robot_iatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_audio::robot_iat >::value();
  }
  static const char* value(const ::robot_audio::robot_iatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_audio::robot_iatResponse> should match
// service_traits::DataType< ::robot_audio::robot_iat >
template<>
struct DataType< ::robot_audio::robot_iatResponse>
{
  static const char* value()
  {
    return DataType< ::robot_audio::robot_iat >::value();
  }
  static const char* value(const ::robot_audio::robot_iatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_ROBOT_IAT_H
