// Generated by gencpp from file robot_audio/robot_semantemeResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_ROBOT_SEMANTEMERESPONSE_H
#define ROBOT_AUDIO_MESSAGE_ROBOT_SEMANTEMERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_audio
{
template <class ContainerAllocator>
struct robot_semantemeResponse_
{
  typedef robot_semantemeResponse_<ContainerAllocator> Type;

  robot_semantemeResponse_()
    : tech()
    , iat()
    , anwser()
    , intent()
    , slots_name()
    , slots_value()  {
    }
  robot_semantemeResponse_(const ContainerAllocator& _alloc)
    : tech(_alloc)
    , iat(_alloc)
    , anwser(_alloc)
    , intent(_alloc)
    , slots_name(_alloc)
    , slots_value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _tech_type;
  _tech_type tech;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _iat_type;
  _iat_type iat;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _anwser_type;
  _anwser_type anwser;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _intent_type;
  _intent_type intent;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _slots_name_type;
  _slots_name_type slots_name;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _slots_value_type;
  _slots_value_type slots_value;





  typedef boost::shared_ptr< ::robot_audio::robot_semantemeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_audio::robot_semantemeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct robot_semantemeResponse_

typedef ::robot_audio::robot_semantemeResponse_<std::allocator<void> > robot_semantemeResponse;

typedef boost::shared_ptr< ::robot_audio::robot_semantemeResponse > robot_semantemeResponsePtr;
typedef boost::shared_ptr< ::robot_audio::robot_semantemeResponse const> robot_semantemeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_audio::robot_semantemeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_audio::robot_semantemeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_audio::robot_semantemeResponse_<ContainerAllocator1> & lhs, const ::robot_audio::robot_semantemeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.tech == rhs.tech &&
    lhs.iat == rhs.iat &&
    lhs.anwser == rhs.anwser &&
    lhs.intent == rhs.intent &&
    lhs.slots_name == rhs.slots_name &&
    lhs.slots_value == rhs.slots_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_audio::robot_semantemeResponse_<ContainerAllocator1> & lhs, const ::robot_audio::robot_semantemeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_audio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_audio::robot_semantemeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_audio::robot_semantemeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::robot_semantemeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::robot_semantemeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::robot_semantemeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::robot_semantemeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_audio::robot_semantemeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77f681fe0c5d79108436880fba11f4b6";
  }

  static const char* value(const ::robot_audio::robot_semantemeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77f681fe0c5d7910ULL;
  static const uint64_t static_value2 = 0x8436880fba11f4b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_audio::robot_semantemeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_audio/robot_semantemeResponse";
  }

  static const char* value(const ::robot_audio::robot_semantemeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_audio::robot_semantemeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string tech\n"
"string iat\n"
"string anwser\n"
"string intent\n"
"string[] slots_name\n"
"string[] slots_value\n"
"\n"
;
  }

  static const char* value(const ::robot_audio::robot_semantemeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_audio::robot_semantemeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tech);
      stream.next(m.iat);
      stream.next(m.anwser);
      stream.next(m.intent);
      stream.next(m.slots_name);
      stream.next(m.slots_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_semantemeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_audio::robot_semantemeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_audio::robot_semantemeResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "tech: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.tech);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "iat: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.iat);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "anwser: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.anwser);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "intent: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.intent);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "slots_name: ";
    if (v.slots_name.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.slots_name.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.slots_name[i]);
    }
    if (v.slots_name.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "slots_value: ";
    if (v.slots_value.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.slots_value.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.slots_value[i]);
    }
    if (v.slots_value.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_ROBOT_SEMANTEMERESPONSE_H
