// Generated by gencpp from file robot_audio/robot_iatResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_ROBOT_IATRESPONSE_H
#define ROBOT_AUDIO_MESSAGE_ROBOT_IATRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_audio
{
template <class ContainerAllocator>
struct robot_iatResponse_
{
  typedef robot_iatResponse_<ContainerAllocator> Type;

  robot_iatResponse_()
    : text()  {
    }
  robot_iatResponse_(const ContainerAllocator& _alloc)
    : text(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::robot_audio::robot_iatResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_audio::robot_iatResponse_<ContainerAllocator> const> ConstPtr;

}; // struct robot_iatResponse_

typedef ::robot_audio::robot_iatResponse_<std::allocator<void> > robot_iatResponse;

typedef boost::shared_ptr< ::robot_audio::robot_iatResponse > robot_iatResponsePtr;
typedef boost::shared_ptr< ::robot_audio::robot_iatResponse const> robot_iatResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_audio::robot_iatResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_audio::robot_iatResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_audio::robot_iatResponse_<ContainerAllocator1> & lhs, const ::robot_audio::robot_iatResponse_<ContainerAllocator2> & rhs)
{
  return lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_audio::robot_iatResponse_<ContainerAllocator1> & lhs, const ::robot_audio::robot_iatResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_audio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_audio::robot_iatResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_audio::robot_iatResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::robot_iatResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::robot_iatResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::robot_iatResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::robot_iatResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_audio::robot_iatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74697ed3d931f6eede8bf3a8dfeca160";
  }

  static const char* value(const ::robot_audio::robot_iatResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74697ed3d931f6eeULL;
  static const uint64_t static_value2 = 0xde8bf3a8dfeca160ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_audio::robot_iatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_audio/robot_iatResponse";
  }

  static const char* value(const ::robot_audio::robot_iatResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_audio::robot_iatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text\n"
"\n"
;
  }

  static const char* value(const ::robot_audio::robot_iatResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_audio::robot_iatResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_iatResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_audio::robot_iatResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_audio::robot_iatResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_ROBOT_IATRESPONSE_H
