// Generated by gencpp from file robot_audio/up_sync.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_UP_SYNC_H
#define ROBOT_AUDIO_MESSAGE_UP_SYNC_H

#include <ros/service_traits.h>


#include <robot_audio/up_syncRequest.h>
#include <robot_audio/up_syncResponse.h>


namespace robot_audio
{

struct up_sync
{

typedef up_syncRequest Request;
typedef up_syncResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct up_sync
} // namespace robot_audio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_audio::up_sync > {
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::robot_audio::up_sync&) { return value(); }
};

template<>
struct DataType< ::robot_audio::up_sync > {
  static const char* value()
  {
    return "robot_audio/up_sync";
  }

  static const char* value(const ::robot_audio::up_sync&) { return value(); }
};


// service_traits::MD5Sum< ::robot_audio::up_syncRequest> should match
// service_traits::MD5Sum< ::robot_audio::up_sync >
template<>
struct MD5Sum< ::robot_audio::up_syncRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_audio::up_sync >::value();
  }
  static const char* value(const ::robot_audio::up_syncRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_audio::up_syncRequest> should match
// service_traits::DataType< ::robot_audio::up_sync >
template<>
struct DataType< ::robot_audio::up_syncRequest>
{
  static const char* value()
  {
    return DataType< ::robot_audio::up_sync >::value();
  }
  static const char* value(const ::robot_audio::up_syncRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_audio::up_syncResponse> should match
// service_traits::MD5Sum< ::robot_audio::up_sync >
template<>
struct MD5Sum< ::robot_audio::up_syncResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_audio::up_sync >::value();
  }
  static const char* value(const ::robot_audio::up_syncResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_audio::up_syncResponse> should match
// service_traits::DataType< ::robot_audio::up_sync >
template<>
struct DataType< ::robot_audio::up_syncResponse>
{
  static const char* value()
  {
    return DataType< ::robot_audio::up_sync >::value();
  }
  static const char* value(const ::robot_audio::up_syncResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_UP_SYNC_H
