// Generated by gencpp from file robot_audio/up_syncRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_AUDIO_MESSAGE_UP_SYNCREQUEST_H
#define ROBOT_AUDIO_MESSAGE_UP_SYNCREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_audio
{
template <class ContainerAllocator>
struct up_syncRequest_
{
  typedef up_syncRequest_<ContainerAllocator> Type;

  up_syncRequest_()
    {
    }
  up_syncRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::robot_audio::up_syncRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_audio::up_syncRequest_<ContainerAllocator> const> ConstPtr;

}; // struct up_syncRequest_

typedef ::robot_audio::up_syncRequest_<std::allocator<void> > up_syncRequest;

typedef boost::shared_ptr< ::robot_audio::up_syncRequest > up_syncRequestPtr;
typedef boost::shared_ptr< ::robot_audio::up_syncRequest const> up_syncRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_audio::up_syncRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_audio::up_syncRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace robot_audio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_audio::up_syncRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_audio::up_syncRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::up_syncRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_audio::up_syncRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::up_syncRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_audio::up_syncRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_audio::up_syncRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::robot_audio::up_syncRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_audio::up_syncRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_audio/up_syncRequest";
  }

  static const char* value(const ::robot_audio::up_syncRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_audio::up_syncRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::robot_audio::up_syncRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_audio::up_syncRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct up_syncRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_audio::up_syncRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::robot_audio::up_syncRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_AUDIO_MESSAGE_UP_SYNCREQUEST_H
