// Generated by gencpp from file face_rec/face_data.msg
// DO NOT EDIT!


#ifndef FACE_REC_MESSAGE_FACE_DATA_H
#define FACE_REC_MESSAGE_FACE_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace face_rec
{
template <class ContainerAllocator>
struct face_data_
{
  typedef face_data_<ContainerAllocator> Type;

  face_data_()
    : name()
    , xmin(0.0)
    , xmax(0.0)
    , ymin(0.0)
    , ymax(0.0)  {
    }
  face_data_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , xmin(0.0)
    , xmax(0.0)
    , ymin(0.0)
    , ymax(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef double _xmin_type;
  _xmin_type xmin;

   typedef double _xmax_type;
  _xmax_type xmax;

   typedef double _ymin_type;
  _ymin_type ymin;

   typedef double _ymax_type;
  _ymax_type ymax;





  typedef boost::shared_ptr< ::face_rec::face_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::face_rec::face_data_<ContainerAllocator> const> ConstPtr;

}; // struct face_data_

typedef ::face_rec::face_data_<std::allocator<void> > face_data;

typedef boost::shared_ptr< ::face_rec::face_data > face_dataPtr;
typedef boost::shared_ptr< ::face_rec::face_data const> face_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::face_rec::face_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::face_rec::face_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::face_rec::face_data_<ContainerAllocator1> & lhs, const ::face_rec::face_data_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.xmin == rhs.xmin &&
    lhs.xmax == rhs.xmax &&
    lhs.ymin == rhs.ymin &&
    lhs.ymax == rhs.ymax;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::face_rec::face_data_<ContainerAllocator1> & lhs, const ::face_rec::face_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace face_rec

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::face_rec::face_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_rec::face_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_rec::face_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_rec::face_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_rec::face_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_rec::face_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::face_rec::face_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cac4f3cdaff898e913e562b59bf6e65e";
  }

  static const char* value(const ::face_rec::face_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcac4f3cdaff898e9ULL;
  static const uint64_t static_value2 = 0x13e562b59bf6e65eULL;
};

template<class ContainerAllocator>
struct DataType< ::face_rec::face_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face_rec/face_data";
  }

  static const char* value(const ::face_rec::face_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::face_rec::face_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"float64 xmin\n"
"float64 xmax\n"
"float64 ymin\n"
"float64 ymax\n"
;
  }

  static const char* value(const ::face_rec::face_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::face_rec::face_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.xmin);
      stream.next(m.xmax);
      stream.next(m.ymin);
      stream.next(m.ymax);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct face_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::face_rec::face_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::face_rec::face_data_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "xmin: ";
    Printer<double>::stream(s, indent + "  ", v.xmin);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "xmax: ";
    Printer<double>::stream(s, indent + "  ", v.xmax);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ymin: ";
    Printer<double>::stream(s, indent + "  ", v.ymin);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ymax: ";
    Printer<double>::stream(s, indent + "  ", v.ymax);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACE_REC_MESSAGE_FACE_DATA_H
