// Generated by gencpp from file face_rec/recognition_resultsRequest.msg
// DO NOT EDIT!


#ifndef FACE_REC_MESSAGE_RECOGNITION_RESULTSREQUEST_H
#define FACE_REC_MESSAGE_RECOGNITION_RESULTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace face_rec
{
template <class ContainerAllocator>
struct recognition_resultsRequest_
{
  typedef recognition_resultsRequest_<ContainerAllocator> Type;

  recognition_resultsRequest_()
    : mode(0)
    , image_path()  {
    }
  recognition_resultsRequest_(const ContainerAllocator& _alloc)
    : mode(0)
    , image_path(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _mode_type;
  _mode_type mode;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _image_path_type;
  _image_path_type image_path;





  typedef boost::shared_ptr< ::face_rec::recognition_resultsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::face_rec::recognition_resultsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct recognition_resultsRequest_

typedef ::face_rec::recognition_resultsRequest_<std::allocator<void> > recognition_resultsRequest;

typedef boost::shared_ptr< ::face_rec::recognition_resultsRequest > recognition_resultsRequestPtr;
typedef boost::shared_ptr< ::face_rec::recognition_resultsRequest const> recognition_resultsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::face_rec::recognition_resultsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::face_rec::recognition_resultsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::face_rec::recognition_resultsRequest_<ContainerAllocator1> & lhs, const ::face_rec::recognition_resultsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.image_path == rhs.image_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::face_rec::recognition_resultsRequest_<ContainerAllocator1> & lhs, const ::face_rec::recognition_resultsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace face_rec

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::face_rec::recognition_resultsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_rec::recognition_resultsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_rec::recognition_resultsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_rec::recognition_resultsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_rec::recognition_resultsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_rec::recognition_resultsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::face_rec::recognition_resultsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b0e7560dc21d6956d378e96d296c64a6";
  }

  static const char* value(const ::face_rec::recognition_resultsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb0e7560dc21d6956ULL;
  static const uint64_t static_value2 = 0xd378e96d296c64a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::face_rec::recognition_resultsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face_rec/recognition_resultsRequest";
  }

  static const char* value(const ::face_rec::recognition_resultsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::face_rec::recognition_resultsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 mode\n"
"string image_path\n"
;
  }

  static const char* value(const ::face_rec::recognition_resultsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::face_rec::recognition_resultsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.image_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct recognition_resultsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::face_rec::recognition_resultsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::face_rec::recognition_resultsRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "image_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.image_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACE_REC_MESSAGE_RECOGNITION_RESULTSREQUEST_H
