// Generated by gencpp from file face_rec/recognition_resultsResponse.msg
// DO NOT EDIT!


#ifndef FACE_REC_MESSAGE_RECOGNITION_RESULTSRESPONSE_H
#define FACE_REC_MESSAGE_RECOGNITION_RESULTSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <face_rec/face_results.h>

namespace face_rec
{
template <class ContainerAllocator>
struct recognition_resultsResponse_
{
  typedef recognition_resultsResponse_<ContainerAllocator> Type;

  recognition_resultsResponse_()
    : result()
    , success(false)  {
    }
  recognition_resultsResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef  ::face_rec::face_results_<ContainerAllocator>  _result_type;
  _result_type result;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::face_rec::recognition_resultsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::face_rec::recognition_resultsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct recognition_resultsResponse_

typedef ::face_rec::recognition_resultsResponse_<std::allocator<void> > recognition_resultsResponse;

typedef boost::shared_ptr< ::face_rec::recognition_resultsResponse > recognition_resultsResponsePtr;
typedef boost::shared_ptr< ::face_rec::recognition_resultsResponse const> recognition_resultsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::face_rec::recognition_resultsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::face_rec::recognition_resultsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::face_rec::recognition_resultsResponse_<ContainerAllocator1> & lhs, const ::face_rec::recognition_resultsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::face_rec::recognition_resultsResponse_<ContainerAllocator1> & lhs, const ::face_rec::recognition_resultsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace face_rec

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::face_rec::recognition_resultsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_rec::recognition_resultsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_rec::recognition_resultsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_rec::recognition_resultsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_rec::recognition_resultsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_rec::recognition_resultsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::face_rec::recognition_resultsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22bd2b1480094425ede2ba2224be1250";
  }

  static const char* value(const ::face_rec::recognition_resultsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22bd2b1480094425ULL;
  static const uint64_t static_value2 = 0xede2ba2224be1250ULL;
};

template<class ContainerAllocator>
struct DataType< ::face_rec::recognition_resultsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face_rec/recognition_resultsResponse";
  }

  static const char* value(const ::face_rec::recognition_resultsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::face_rec::recognition_resultsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face_rec/face_results result\n"
"bool success\n"
"\n"
"================================================================================\n"
"MSG: face_rec/face_results\n"
"uint8 num\n"
"face_rec/face_data[] face_data\n"
"================================================================================\n"
"MSG: face_rec/face_data\n"
"string name\n"
"float64 xmin\n"
"float64 xmax\n"
"float64 ymin\n"
"float64 ymax\n"
;
  }

  static const char* value(const ::face_rec::recognition_resultsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::face_rec::recognition_resultsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct recognition_resultsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::face_rec::recognition_resultsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::face_rec::recognition_resultsResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "result: ";
    Printer< ::face_rec::face_results_<ContainerAllocator> >::stream(s, indent + "  ", v.result);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACE_REC_MESSAGE_RECOGNITION_RESULTSRESPONSE_H
