// Generated by gencpp from file relative_move/SetRelativeMoveRequest.msg
// DO NOT EDIT!


#ifndef RELATIVE_MOVE_MESSAGE_SETRELATIVEMOVEREQUEST_H
#define RELATIVE_MOVE_MESSAGE_SETRELATIVEMOVEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace relative_move
{
template <class ContainerAllocator>
struct SetRelativeMoveRequest_
{
  typedef SetRelativeMoveRequest_<ContainerAllocator> Type;

  SetRelativeMoveRequest_()
    : goal()
    , global_frame()
    , avoid_obstacle(false)
    , finishStopObstacle(false)  {
    }
  SetRelativeMoveRequest_(const ContainerAllocator& _alloc)
    : goal(_alloc)
    , global_frame(_alloc)
    , avoid_obstacle(false)
    , finishStopObstacle(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _goal_type;
  _goal_type goal;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _global_frame_type;
  _global_frame_type global_frame;

   typedef uint8_t _avoid_obstacle_type;
  _avoid_obstacle_type avoid_obstacle;

   typedef uint8_t _finishStopObstacle_type;
  _finishStopObstacle_type finishStopObstacle;





  typedef boost::shared_ptr< ::relative_move::SetRelativeMoveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::relative_move::SetRelativeMoveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRelativeMoveRequest_

typedef ::relative_move::SetRelativeMoveRequest_<std::allocator<void> > SetRelativeMoveRequest;

typedef boost::shared_ptr< ::relative_move::SetRelativeMoveRequest > SetRelativeMoveRequestPtr;
typedef boost::shared_ptr< ::relative_move::SetRelativeMoveRequest const> SetRelativeMoveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::relative_move::SetRelativeMoveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::relative_move::SetRelativeMoveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::relative_move::SetRelativeMoveRequest_<ContainerAllocator1> & lhs, const ::relative_move::SetRelativeMoveRequest_<ContainerAllocator2> & rhs)
{
  return lhs.goal == rhs.goal &&
    lhs.global_frame == rhs.global_frame &&
    lhs.avoid_obstacle == rhs.avoid_obstacle &&
    lhs.finishStopObstacle == rhs.finishStopObstacle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::relative_move::SetRelativeMoveRequest_<ContainerAllocator1> & lhs, const ::relative_move::SetRelativeMoveRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace relative_move

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::relative_move::SetRelativeMoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::relative_move::SetRelativeMoveRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::relative_move::SetRelativeMoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::relative_move::SetRelativeMoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::relative_move::SetRelativeMoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::relative_move::SetRelativeMoveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::relative_move::SetRelativeMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95e0b62a1da2ec483697d85f4f0775da";
  }

  static const char* value(const ::relative_move::SetRelativeMoveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95e0b62a1da2ec48ULL;
  static const uint64_t static_value2 = 0x3697d85f4f0775daULL;
};

template<class ContainerAllocator>
struct DataType< ::relative_move::SetRelativeMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "relative_move/SetRelativeMoveRequest";
  }

  static const char* value(const ::relative_move::SetRelativeMoveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::relative_move::SetRelativeMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D goal\n"
"string global_frame #map odom\n"
"bool avoid_obstacle\n"
"bool finishStopObstacle #停障碍时是否直接结束\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::relative_move::SetRelativeMoveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::relative_move::SetRelativeMoveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
      stream.next(m.global_frame);
      stream.next(m.avoid_obstacle);
      stream.next(m.finishStopObstacle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRelativeMoveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::relative_move::SetRelativeMoveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::relative_move::SetRelativeMoveRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
    s << indent << "global_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.global_frame);
    s << indent << "avoid_obstacle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.avoid_obstacle);
    s << indent << "finishStopObstacle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finishStopObstacle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RELATIVE_MOVE_MESSAGE_SETRELATIVEMOVEREQUEST_H
