// Generated by gencpp from file ar_pose/Track.msg
// DO NOT EDIT!


#ifndef AR_POSE_MESSAGE_TRACK_H
#define AR_POSE_MESSAGE_TRACK_H

#include <ros/service_traits.h>


#include <ar_pose/TrackRequest.h>
#include <ar_pose/TrackResponse.h>


namespace ar_pose
{

struct Track
{

typedef TrackRequest Request;
typedef TrackResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Track
} // namespace ar_pose


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ar_pose::Track > {
  static const char* value()
  {
    return "a9830d64a630dd3c64bf976a0539314c";
  }

  static const char* value(const ::ar_pose::Track&) { return value(); }
};

template<>
struct DataType< ::ar_pose::Track > {
  static const char* value()
  {
    return "ar_pose/Track";
  }

  static const char* value(const ::ar_pose::Track&) { return value(); }
};


// service_traits::MD5Sum< ::ar_pose::TrackRequest> should match
// service_traits::MD5Sum< ::ar_pose::Track >
template<>
struct MD5Sum< ::ar_pose::TrackRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ar_pose::Track >::value();
  }
  static const char* value(const ::ar_pose::TrackRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ar_pose::TrackRequest> should match
// service_traits::DataType< ::ar_pose::Track >
template<>
struct DataType< ::ar_pose::TrackRequest>
{
  static const char* value()
  {
    return DataType< ::ar_pose::Track >::value();
  }
  static const char* value(const ::ar_pose::TrackRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ar_pose::TrackResponse> should match
// service_traits::MD5Sum< ::ar_pose::Track >
template<>
struct MD5Sum< ::ar_pose::TrackResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ar_pose::Track >::value();
  }
  static const char* value(const ::ar_pose::TrackResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ar_pose::TrackResponse> should match
// service_traits::DataType< ::ar_pose::Track >
template<>
struct DataType< ::ar_pose::TrackResponse>
{
  static const char* value()
  {
    return DataType< ::ar_pose::Track >::value();
  }
  static const char* value(const ::ar_pose::TrackResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AR_POSE_MESSAGE_TRACK_H
