// Generated by gencpp from file ar_pose/TrackResponse.msg
// DO NOT EDIT!


#ifndef AR_POSE_MESSAGE_TRACKRESPONSE_H
#define AR_POSE_MESSAGE_TRACKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ar_pose
{
template <class ContainerAllocator>
struct TrackResponse_
{
  typedef TrackResponse_<ContainerAllocator> Type;

  TrackResponse_()
    : message()
    , success(false)  {
    }
  TrackResponse_(const ContainerAllocator& _alloc)
    : message(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::ar_pose::TrackResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ar_pose::TrackResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TrackResponse_

typedef ::ar_pose::TrackResponse_<std::allocator<void> > TrackResponse;

typedef boost::shared_ptr< ::ar_pose::TrackResponse > TrackResponsePtr;
typedef boost::shared_ptr< ::ar_pose::TrackResponse const> TrackResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ar_pose::TrackResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ar_pose::TrackResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ar_pose::TrackResponse_<ContainerAllocator1> & lhs, const ::ar_pose::TrackResponse_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ar_pose::TrackResponse_<ContainerAllocator1> & lhs, const ::ar_pose::TrackResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ar_pose

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ar_pose::TrackResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ar_pose::TrackResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ar_pose::TrackResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ar_pose::TrackResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ar_pose::TrackResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ar_pose::TrackResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ar_pose::TrackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bf829f07d795d3f9e541a07897da2c4";
  }

  static const char* value(const ::ar_pose::TrackResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bf829f07d795d3fULL;
  static const uint64_t static_value2 = 0x9e541a07897da2c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::ar_pose::TrackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ar_pose/TrackResponse";
  }

  static const char* value(const ::ar_pose::TrackResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ar_pose::TrackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
"bool success\n"
;
  }

  static const char* value(const ::ar_pose::TrackResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ar_pose::TrackResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ar_pose::TrackResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ar_pose::TrackResponse_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AR_POSE_MESSAGE_TRACKRESPONSE_H
