(cl:defpackage face_rec-srv
  (:use )
  (:export
   "RECOGNITION_RESULTS"
   "<RECOGNITION_RESULTS-REQUEST>"
   "RECOGNITION_RESULTS-REQUEST"
   "<RECOGNITION_RESULTS-RESPONSE>"
   "RECOGNITION_RESULTS-RESPONSE"
  ))

